name: mercure-totalsegmentator
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dcm2niix
  - pydicom
  - jupyterlab
  - pip
  - pip :
    - scikit-learn==1.2.0
    - TotalSegmentator==2.4.0
    - monai-deploy-app-sdk==0.5.0
    - matplotlib==3.6.2
    - typeguard==2.12.1
    - highdicom==0.22.0
    - rt-utils==1.2.7
    - torch==2.4.1
    - acvl_utils==0.2